#!/bin/bash

x=`whoami`
kill -9 `cat /tmp/redis.$x.pid`
kill -9 `cat /tmp/gunicorn.$x.pid` 
kill -9 `cat /tmp/rqworker.$x.1.pid` 
kill -9 `cat /tmp/rqworker.$x.2.pid` 
kill -9 `cat /tmp/rqworker.$x.3.pid` 
kill -9 `cat /tmp/rqworker.$x.4.pid` 
kill -9 `cat /tmp/rqworker.$x.5.pid` 
kill -9 `cat /tmp/rqworker.$x.6.pid` 
