#!/bin/bash

kill -9 `cat /tmp/redis.pid`
kill -9 `cat /tmp/gunicorn.pid` 
kill -9 `cat /tmp/rqworker1.pid` 
kill -9 `cat /tmp/rqworker2.pid` 
kill -9 `cat /tmp/rqworker3.pid` 
kill -9 `cat /tmp/rqworker4.pid` 
kill -9 `cat /tmp/rqworker5.pid` 
kill -9 `cat /tmp/rqworker6.pid` 
