#!/bin/bash
#
# loop in case it ever dies when in debug mode
# don't use this in production!

mkdir processing 2>&1 >/dev/null

kill `cat /tmp/rqworker1.pid`
kill `cat /tmp/rqworker2.pid`
kill `cat /tmp/rqworker3.pid`
rqworker --pid /tmp/rqworker1.pid &
rqworker --pid /tmp/rqworker2.pid &
rqworker --pid /tmp/rqworker3.pid &
./MasterApp.py
kill `cat /tmp/rqworker1.pid`
kill `cat /tmp/rqworker2.pid`
kill `cat /tmp/rqworker3.pid`


# in production use gunicorn like so:
#  gunicorn -w 4 -b 127.0.0.1:5000 MasterApp:app
