#!/bin/bash

x=`whoami`
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
mkdir -p processing 2>&1 >/dev/null

$DIR/kill_server
redis-server --daemonize yes --pidfile /tmp/redis.$x.pid --logfile /tmp/redis.$x.log
for i in {1..6}; do
  rqworker --pid /tmp/rqworker.$x.$i.pid &
done
