#!/bin/bash
#
# don't use this in production!

mkdir processing 2>&1 >/dev/null

kill `cat /tmp/rqworker1.pid`
kill `cat /tmp/rqworker2.pid`
kill `cat /tmp/rqworker3.pid`
rqworker --pid /tmp/rqworker1.pid &
rqworker --pid /tmp/rqworker2.pid &
rqworker --pid /tmp/rqworker3.pid &
./MasterApp.py
kill `cat /tmp/rqworker1.pid`
kill `cat /tmp/rqworker2.pid`
kill `cat /tmp/rqworker3.pid`

